/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "surface": "#f9f9ff",
        "primary-fixed": "#ffdad8",
        "on-error": "#ffffff",
        "surface-light": "#F4F5F7",
        "primary": "#9e001f",
        "on-tertiary": "#ffffff",
        "tertiary-fixed": "#e1e2e6",
        "inverse-primary": "#ffb3b1",
        "tertiary-fixed-dim": "#c5c6ca",
        "on-tertiary-container": "#e1e3e6",
        "primary-container": "#c8102e",
        "on-secondary-fixed-variant": "#2c476f",
        "inverse-surface": "#29313e",
        "on-tertiary-fixed-variant": "#44474a",
        "on-secondary-container": "#3e5981",
        "surface-variant": "#dbe3f4",
        "on-error-container": "#93000a",
        "surface-dim": "#d2daec",
        "on-secondary": "#ffffff",
        "on-primary": "#ffffff",
        "primary-fixed-dim": "#ffb3b1",
        "on-primary-container": "#ffdad8",
        "error": "#ba1a1a",
        "secondary-container": "#b5d0ff",
        "accent-red-hover": "#A50D26",
        "secondary-fixed": "#d5e3ff",
        "on-surface": "#141c28",
        "surface-container-low": "#f0f3ff",
        "on-primary-fixed": "#410007",
        "on-secondary-fixed": "#001b3c",
        "surface-container-highest": "#dbe3f4",
        "on-primary-fixed-variant": "#92001c",
        "secondary-fixed-dim": "#adc8f6",
        "error-container": "#ffdad6",
        "outline": "#906f6e",
        "surface-container": "#e7eeff",
        "on-background": "#141c28",
        "secondary": "#455f88",
        "surface-container-high": "#e0e8fa",
        "surface-dark": "#002349",
        "on-tertiary-fixed": "#191c1e",
        "flow-silver": "#E2E4E7",
        "tertiary-container": "#626568",
        "surface-container-lowest": "#ffffff",
        "outline-variant": "#e5bdbb",
        "background": "#f9f9ff",
        "on-surface-variant": "#5c403f",
        "tertiary": "#4a4d50",
        "surface-tint": "#bf0229",
        "surface-bright": "#f9f9ff",
        "inverse-on-surface": "#ebf1ff"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      fontFamily: {
        sans: ["Inter", "sans-serif"],
        display: ["Outfit", "sans-serif"],
      }
    },
  },
  plugins: [],
}
